version: '3.1'
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Uncomment volumes parameter to persist db data when container is removed
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql
